apiVersion: storage.k8s.io/v1
kind: StorageClass

metadata:
  name: efs-storage-class

provisioner: efs.csi.aws.com
parameters:
  provisioningMode: efs-ap
  fileSystemId: fs-01d26b63ee6bcc780
  directoryPerms: "700"
