apiVersion: apps/v1
kind: Deployment

metadata:
  name: express-deploy
spec:
  replicas: 3
  selector:
    matchLabels:
      app: mongo
      tier: server
  template:
    metadata:
      name: express-pod
      labels:
        app: mongo
        tier: server
    spec:
      containers:
        - name: express
          image: mongo-express
          ports:
            - containerPort: 8081
          env:
            - name: ME_CONFIG_MONGODB_SERVER
              value: mongo-service
            - name: ME_CONFIG_MONGODB_PORT
              value: "27017"
            - name: ME_CONFIG_MONGODB_ENABLE_ADMIN
              value: "true"
            - name: ME_CONFIG_MONGODB_ADMINUSERNAME
              valueFrom:
                secretKeyRef:
                  name: mongo-secret
                  key: username
            - name: ME_CONFIG_MONGODB_ADMINPASSWORD
              valueFrom:
                secretKeyRef:
                  name: mongo-secret
                  key: password
