apiVersion: v1
kind: Service
metadata:
  name: express-service
spec:
  type: NodePort
  selector:
    app: mongo
    tier: server
  ports:
    - nodePort: 31031
      port: 8081
      targetPort: 8081
