apiVersion: v1
kind: PersistentVolumeClaim

metadata:
  name: mongo-pvc2
spec:
  resources:
    requests:
      storage: 5Gi
  storageClassName: mongo-sc
  accessModes:
    - ReadWriteOnce
  volumeName: mongo-pv2 
