apiVersion: apps/v1
kind: Deployment

metadata:
  name: mongo-deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongo
      tier: db
  template:
    metadata:
      name: mongo-pod
      labels:
        app: mongo
        tier: db
    spec:
      containers:
        - name: mongodb
          image: mongo:6.0
          ports:
            - containerPort: 27017
          env:
            - name: MONGO_INITDB_ROOT_USERNAME
              valueFrom:
                secretKeyRef:
                  name: mongo-secret
                  key: username
            - name: MONGO_INITDB_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mongo-secret
                  key: password
          volumeMounts:
            - mountPath: /data/db
              name: mongo-pv
      volumes:
        - name: mongo-pv
          persistentVolumeClaim:
            claimName: mongo-pvc2
