apiVersion: v1
kind: Service

metadata:
  name: mysql-service
spec:
  selector:
    app: wordpress
    tier: mysql
  type: ClusterIP
  ports:
    - port: 3306
      targetPort: 3306
      name: mysql

