apiVersion: apps/v1
kind: Deployment

metadata:
  name: mysql-deploy
spec:
  selector:
    matchLabels:
      app: wordpress
      tier: mysql
  template:
    metadata:
      name: mysql-pod
      labels:
        app: wordpress
        tier: mysql
    spec:
      containers:
        - image: mysql:5.6
          name: mysql
          volumeMounts:
            - name: mysql-pv
              mountPath: /var/lib/mysql
          env:
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: password
                  name: mysql-secret
          ports:
            - containerPort: 3306
      volumes:
        - name: mysql-pv
          persistentVolumeClaim:
            claimName: ebs-pvc
